/*
 * role-overlay-citus-patroni-bootstrap.tf -- Phase 0.P
 *
 * One-shot, per Patroni SCOPE (3 groups: citus-coord, citus-worker1,
 * citus-worker2): render /etc/patroni/patroni.yml on the group's 2 nodes,
 * write the postgres ~/.pgpass (for Citus inter-node libpq auth), start
 * nexus-patroni.service in PARALLEL within the group, wait for 1 Leader + 1
 * streaming Replica + a psql round-trip on the leader.
 *
 * All 3 groups share the one etcd DCS under distinct namespaces
 * (/citus/<scope>). Each PG cluster carries `shared_preload_libraries=citus`
 * so the Citus extension can be created post-bootstrap; `citus.node_conninfo`
 * makes the coordinator dial workers over verify-full mTLS (presenting its own
 * 0600 postgres-owned client key). pg_hba uses `clientcert=verify-ca` so every
 * connection (clients, inter-node, replication) must present a CA-signed cert
 * AND a scram password -- true mTLS. The shared superuser/replication
 * passwords (KV-seeded, same cluster-wide) live in ~postgres/.pgpass so
 * libpq-based inter-node + replication connections authenticate without
 * embedding the password in node_conninfo (Citus forbids that).
 *
 * etcd3 DCS auth = client cert (no username/password) -- etcd runs
 * client-cert-auth=true; Patroni presents its leaf.
 *
 * Selective ops: var.enable_patroni_bootstrap. Pre-req: etcd bootstrapped;
 * citus-tls rendered tls/* + the 4 KV creds on the 6 pg nodes.
 */

locals {
  citus_pg_nodes = {
    "citus-coord-1"   = { vm_ip = "192.168.70.205", peer_ip = "192.168.10.205", group = "coord", scope = "citus-coord", enabled = var.enable_coord_1 }
    "citus-coord-2"   = { vm_ip = "192.168.70.206", peer_ip = "192.168.10.206", group = "coord", scope = "citus-coord", enabled = var.enable_coord_2 }
    "citus-worker1-1" = { vm_ip = "192.168.70.207", peer_ip = "192.168.10.207", group = "worker1", scope = "citus-worker1", enabled = var.enable_worker1_1 }
    "citus-worker1-2" = { vm_ip = "192.168.70.208", peer_ip = "192.168.10.208", group = "worker1", scope = "citus-worker1", enabled = var.enable_worker1_2 }
    "citus-worker2-1" = { vm_ip = "192.168.70.209", peer_ip = "192.168.10.209", group = "worker2", scope = "citus-worker2", enabled = var.enable_worker2_1 }
    "citus-worker2-2" = { vm_ip = "192.168.70.210", peer_ip = "192.168.10.210", group = "worker2", scope = "citus-worker2", enabled = var.enable_worker2_2 }
  }

  citus_pg_nodes_active = {
    for host, m in local.citus_pg_nodes : host => m if m.enabled
  }

  # BARE hostnames (dnsmasq serves bare; .nexus.lab is issuance-only). Patroni
  # etcd3 dials these on :2379 (client-cert-auth, leaf presented).
  citus_patroni_etcd_endpoints = "citus-etcd-1:2379,citus-etcd-2:2379,citus-etcd-3:2379"
}

resource "null_resource" "citus_patroni_bootstrap" {
  count = var.enable_patroni_bootstrap ? 1 : 0

  triggers = {
    tls_ids                   = join(",", [for host in keys(local.citus_pg_nodes_active) : null_resource.citus_tls[host].id])
    etcd_bootstrap_id         = length(null_resource.citus_etcd_bootstrap) > 0 ? null_resource.citus_etcd_bootstrap[0].id : "disabled"
    citus_patroni_bootstrap_v = "1" # v1 (0.P) = 3 Patroni scopes (coord + worker1 + worker2), PG 17 + Citus preload + etcd3 cert-auth DCS + verify-ca mTLS pg_hba.
  }

  depends_on = [null_resource.citus_tls, null_resource.citus_etcd_bootstrap]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser   = '${var.citus_node_user}'
      $sshOpts   = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $etcdHosts = '${local.citus_patroni_etcd_endpoints}'
      $timeout   = ${var.citus_cluster_timeout_minutes}
      $citusDb   = '${var.citus_database}'

      $allNodes = @(
%{for host, m in local.citus_pg_nodes_active~}
        @{ Host='${host}'; VmIp='${m.vm_ip}'; PeerIp='${m.peer_ip}'; Group='${m.group}'; Scope='${m.scope}' },
%{endfor~}
        $null
      ) | Where-Object { $_ -ne $null }

      $groups = $allNodes | Group-Object -Property Scope
      Write-Host "[citus-patroni-bootstrap] $($allNodes.Count) PG nodes across $($groups.Count) Patroni scopes; etcd=$etcdHosts"

      foreach ($g in $groups) {
        $scope = $g.Name
        $nodes = $g.Group
        Write-Host ""
        Write-Host "[citus-patroni-bootstrap] === scope $scope ($($nodes.Count) nodes) ==="

        # ─── Stage 1: render patroni.yml + ~postgres/.pgpass per node ────────
        foreach ($n in $nodes) {
          $configBody = @"
# Generated by role-overlay-citus-patroni-bootstrap.tf -- Phase 0.P
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.
scope: $scope
namespace: /citus/
name: $($n.Host)

restapi:
  listen: 0.0.0.0:8008
  connect_address: $($n.VmIp):8008
  certfile: /etc/nexus-citus/tls/server-cert.pem
  keyfile: /etc/nexus-citus/tls/server-key.pem
  cafile: /etc/nexus-citus/tls/ca.pem
  verify_client: optional
  authentication:
    username: nexusops
    password: __REST_PWD__

etcd3:
  hosts: $etcdHosts
  protocol: https
  cacert: /etc/nexus-citus/tls/ca.pem
  cert: /etc/nexus-citus/tls/server-cert.pem
  key: /etc/nexus-citus/tls/server-key.pem

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 200
        shared_buffers: 256MB
        wal_level: replica
        hot_standby: "on"
        wal_log_hints: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 256MB
        password_encryption: scram-sha-256
        shared_preload_libraries: citus
        max_prepared_transactions: 100
        citus.node_conninfo: "sslmode=verify-full sslrootcert=/etc/nexus-citus/tls/ca.pem sslcert=/etc/nexus-citus/tls/server-cert.pem sslkey=/etc/nexus-citus/tls/server-key.pem"
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    # mTLS everywhere: clientcert=verify-ca requires a CA-signed client cert
    # AND a scram password. Covers clients, Citus inter-node (coordinator dials
    # worker VIPs), and streaming replication. 192.168.0.0/16 spans VMnet10 +
    # VMnet11 (Patroni connect_address is VMnet11; backplane is VMnet10).
    - "hostssl replication replicator 192.168.0.0/16 scram-sha-256 clientcert=verify-ca"
    - "hostssl all all 192.168.0.0/16 scram-sha-256 clientcert=verify-ca"
    - "host all all 127.0.0.1/32 trust"
    - "host replication replicator 127.0.0.1/32 trust"

postgresql:
  listen: 0.0.0.0:5432
  connect_address: $($n.VmIp):5432
  data_dir: /var/lib/nexus-citus/pgdata
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /var/lib/nexus-citus/.pgpass_patroni
  authentication:
    superuser:
      username: postgres
      password: __SUPER_PWD__
      sslmode: verify-ca
      sslrootcert: /etc/nexus-citus/tls/ca.pem
      sslcert: /etc/nexus-citus/tls/server-cert.pem
      sslkey: /etc/nexus-citus/tls/server-key.pem
    replication:
      username: replicator
      password: __REPL_PWD__
      sslmode: verify-ca
      sslrootcert: /etc/nexus-citus/tls/ca.pem
      sslcert: /etc/nexus-citus/tls/server-cert.pem
      sslkey: /etc/nexus-citus/tls/server-key.pem
    rewind:
      username: rewind
      password: __REPL_PWD__
      sslmode: verify-ca
      sslrootcert: /etc/nexus-citus/tls/ca.pem
      sslcert: /etc/nexus-citus/tls/server-cert.pem
      sslkey: /etc/nexus-citus/tls/server-key.pem
  parameters:
    unix_socket_directories: /var/run/nexus-citus
    ssl: "on"
    ssl_cert_file: /etc/nexus-citus/tls/server-cert.pem
    ssl_key_file: /etc/nexus-citus/tls/server-key.pem
    ssl_ca_file: /etc/nexus-citus/tls/ca.pem
    password_encryption: scram-sha-256

watchdog:
  mode: off

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
"@
          $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

          # NOTE on password handling: Patroni 4 eagerly formats
          # `username:password` at config-load for restapi.authentication +
          # postgresql.authentication, expecting LITERAL `password:` keys
          # (password_file: is NOT honored in that path). So substitute the
          # KV-rendered passwords into the template via sed on the node.
          # (0.G.4 transient #10.)
          $stage = @"
set -euo pipefail

SUPER_PWD=`$(sudo cat /etc/nexus-citus/superuser-password)
REPL_PWD=`$(sudo cat /etc/nexus-citus/replication-password)
REST_PWD=`$(sudo cat /etc/nexus-citus/patroni-restapi-password)

for p in "`$SUPER_PWD" "`$REPL_PWD" "`$REST_PWD"; do
  if [ -z "`$p" ]; then
    echo "[citus-patroni-bootstrap stage] ERROR: a KV password file is empty -- citus-tls overlay may not have rendered" >&2
    exit 1
  fi
done

TMP=`$(mktemp)
echo '$configB64' | base64 -d > "`$TMP"
sed -i "s|__SUPER_PWD__|`$SUPER_PWD|g; s|__REPL_PWD__|`$REPL_PWD|g; s|__REST_PWD__|`$REST_PWD|g" "`$TMP"
if grep -q '__SUPER_PWD__\|__REPL_PWD__\|__REST_PWD__' "`$TMP"; then
  echo "[citus-patroni-bootstrap stage] ERROR: placeholder(s) survived sed" >&2
  rm -f "`$TMP"; exit 1
fi
sudo install -m 0640 -o postgres -g postgres "`$TMP" /etc/patroni/patroni.yml
rm -f "`$TMP"

# Ensure systemd creates the unix_socket_directories runtime dir owned by
# postgres on every start. /run is tmpfs + root-owned, so Patroni (postgres)
# cannot mkdir it. A baked unit predating the RuntimeDirectory fix is repaired
# by this idempotent drop-in. (0.P ratification transient T4.)
sudo mkdir -p /etc/systemd/system/nexus-patroni.service.d
printf '[Service]\nRuntimeDirectory=nexus-citus\nRuntimeDirectoryMode=0755\n' | sudo tee /etc/systemd/system/nexus-patroni.service.d/10-runtimedir.conf > /dev/null

# ~postgres/.pgpass for Citus inter-node + replication libpq auth (the
# password half of mTLS; the cert half comes from citus.node_conninfo).
# Citus forbids a password in node_conninfo, so libpq reads it from .pgpass.
PGHOME=`$(getent passwd postgres | cut -d: -f6)
sudo mkdir -p "`$PGHOME"
printf '*:5432:*:postgres:%s\n*:5432:*:replicator:%s\n' "`$SUPER_PWD" "`$REPL_PWD" | sudo tee "`$PGHOME/.pgpass" > /dev/null
sudo chown postgres:postgres "`$PGHOME/.pgpass"
sudo chmod 0600 "`$PGHOME/.pgpass"

sudo systemctl daemon-reload
# Clear any start-limit/failed state from a prior failed bootstrap attempt so
# the start below isn't rejected with "start request repeated too quickly".
sudo systemctl reset-failed nexus-patroni.service 2>/dev/null || true
sudo systemctl enable nexus-patroni.service
echo CONFIG_OK
"@
          $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
          $out = (ssh @sshOpts "$sshUser@$($n.VmIp)" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String).Trim()
          if ($out -notmatch 'CONFIG_OK') {
            throw "[citus-patroni-bootstrap] $($n.Host): patroni.yml staging failed -- $out"
          }
          Write-Host "[citus-patroni-bootstrap] $($n.Host): patroni.yml + .pgpass rendered, service enabled"
        }

        # Parallel start within the group (race for the etcd lease).
        Write-Host "[citus-patroni-bootstrap] starting nexus-patroni on $scope nodes in parallel..."
        $nodes | ForEach-Object -ThrottleLimit 2 -Parallel {
          $n = $_
          $opts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
          # restart (not start) so a re-rendered patroni.yml -- e.g. updated
          # replication SSL conninfo -- is picked up on a bring-up re-run; on a
          # fresh node Patroni isn't running yet so restart == start.
          ssh @opts "$using:sshUser@$($n.VmIp)" "sudo systemctl restart nexus-patroni.service" 2>&1 | Out-Null
        }

        # ─── Stage 2: wait for 1 Leader + 1 streaming Replica ────────────────
        Write-Host "[citus-patroni-bootstrap] waiting for $scope to converge (1 Leader + 1 Replica)..."
        $deadline   = (Get-Date).AddMinutes($timeout)
        $leaderHost = $null
        $converged  = $false
        $firstNode  = $nodes[0]
        while ((Get-Date) -lt $deadline) {
          $listOut = (ssh @sshOpts "$sshUser@$($firstNode.VmIp)" "sudo /usr/local/sbin/nexus-patronictl list --format json 2>/dev/null" 2>&1 | Out-String).Trim()
          if ($listOut -match '\[') {
            try {
              $cluster  = $listOut | ConvertFrom-Json
              $leader   = $cluster | Where-Object { $_.Role -eq 'Leader' } | Select-Object -First 1
              $replicas = $cluster | Where-Object { $_.Role -eq 'Replica' -or $_.Role -eq 'Sync Standby' }
              $running  = $cluster | Where-Object { $_.State -eq 'running' -or $_.State -eq 'streaming' }
              if ($leader -and $replicas.Count -ge 1 -and $running.Count -ge 2) {
                $leaderHost = $leader.Member
                $converged  = $true
                break
              }
            } catch { }
          }
          Start-Sleep -Seconds 5
        }
        if (-not $converged) {
          foreach ($n in $nodes) {
            $j = (ssh @sshOpts "$sshUser@$($n.VmIp)" "sudo journalctl -u nexus-patroni.service --no-pager -n 30" 2>&1 | Out-String)
            Write-Host "--- journal $($n.Host) ---"; Write-Host $j
          }
          throw "[citus-patroni-bootstrap] scope $scope did not converge (1 Leader + 1 Replica) within $timeout min"
        }
        Write-Host "[citus-patroni-bootstrap] scope $scope converged: leader=$leaderHost"

        # ─── Stage 3: psql write/read round-trip on the leader ───────────────
        $leaderNode = $nodes | Where-Object { $_.Host -eq $leaderHost } | Select-Object -First 1
        $rwStage = @'
set -euo pipefail
SOCK_DIR=/var/run/nexus-citus
sudo -u postgres psql -h "$SOCK_DIR" -U postgres -d postgres -tA -c "CREATE TABLE IF NOT EXISTS nexus_smoke (k text PRIMARY KEY, v text);"
sudo -u postgres psql -h "$SOCK_DIR" -U postgres -d postgres -tA -c "INSERT INTO nexus_smoke (k, v) VALUES ('bootstrap', now()::text) ON CONFLICT (k) DO UPDATE SET v = EXCLUDED.v;"
VAL=$(sudo -u postgres psql -h "$SOCK_DIR" -U postgres -d postgres -tA -c "SELECT v FROM nexus_smoke WHERE k = 'bootstrap';")
if [ -z "$VAL" ]; then echo "[citus-patroni-bootstrap rw] ERROR: insert/read empty" >&2; exit 1; fi
echo "[citus-patroni-bootstrap rw] insert+read on leader OK (val=$VAL)"
'@
        $rwB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($rwStage))
        $rwOut = (ssh @sshOpts "$sshUser@$($leaderNode.VmIp)" "echo '$rwB64' | base64 -d | bash" 2>&1 | Out-String)
        if ($LASTEXITCODE -ne 0) {
          Write-Host $rwOut.Trim()
          throw "[citus-patroni-bootstrap] $scope psql round-trip failed (rc=$LASTEXITCODE)"
        }
        Write-Host $rwOut.Trim()
      }

      Write-Host "[citus-patroni-bootstrap] all $($groups.Count) Patroni scopes converged on PG 17 + Citus preload + TLS."
    PWSH
  }
}
