/*
 * role-overlay-citus-etcd-bootstrap.tf -- Phase 0.P
 *
 * One-shot: render /etc/nexus-etcd/etcd.conf.yml on the 3 etcd nodes, write
 * /etc/nexus-etcd/endpoints, start nexus-etcd.service in PARALLEL across all 3
 * (raft needs simultaneous startup for the first `initial-cluster-state: new`
 * bootstrap), wait for leader election, verify a put/get round-trip.
 *
 * Auth model (differs from the 0.G.4 oltp etcd, which used HTTP basic-auth):
 * client-cert-auth=true on BOTH peer + client transports -- mTLS IS the access
 * control (matching the 0.O vitess etcd decision). Patroni dials etcd with its
 * own leaf cert (client EKU); the nexus-etcdctl wrapper presents the etcd
 * node's server cert as its client cert. No etcd RBAC password to manage/rotate.
 * The nftables backplane + the requirement of a CA-signed client cert are the
 * boundary.
 *
 * Why parallel start: raft elects when a quorum (2/3) is reachable; sequential
 * start isolates the first node in pre-vote.
 *
 * Selective ops: var.enable_etcd_bootstrap. Pre-req: citus-tls rendered
 * tls/{server-cert,server-key,ca}.pem on each etcd node.
 */

locals {
  citus_etcd_members = {
    "citus-etcd-1" = { vm_ip = "192.168.70.202", peer_ip = "192.168.10.202", enabled = var.enable_etcd_1 }
    "citus-etcd-2" = { vm_ip = "192.168.70.203", peer_ip = "192.168.10.203", enabled = var.enable_etcd_2 }
    "citus-etcd-3" = { vm_ip = "192.168.70.204", peer_ip = "192.168.10.204", enabled = var.enable_etcd_3 }
  }

  citus_etcd_members_active = {
    for host, m in local.citus_etcd_members : host => m if m.enabled
  }

  # initial-cluster: peers ride the VMnet10 backplane on :2380.
  citus_etcd_initial_cluster = join(",", [
    for host, m in local.citus_etcd_members_active : "${host}=https://${m.peer_ip}:2380"
  ])

  # client endpoints: BARE hostnames (dnsmasq serves bare hostnames + cert SANs
  # include bare host form; .nexus.lab is in allowed_domains for issuance but
  # dnsmasq's domain is nexus.local). Patroni's etcd3 dials these on :2379.
  citus_etcd_client_endpoints = join(",", [
    for host, m in local.citus_etcd_members_active : "https://${host}:2379"
  ])
}

resource "null_resource" "citus_etcd_bootstrap" {
  count = var.enable_etcd_bootstrap ? 1 : 0

  triggers = {
    tls_ids                = join(",", [for host in keys(local.citus_etcd_members_active) : null_resource.citus_tls[host].id])
    members                = local.citus_etcd_initial_cluster
    citus_etcd_bootstrap_v = "1" # v1 (0.P) = 3-member raft, client-cert-auth mTLS, no RBAC password.
  }

  depends_on = [null_resource.citus_tls]

  provisioner "local-exec" {
    when        = create
    interpreter = ["pwsh", "-NoProfile", "-Command"]
    command     = <<-PWSH
      $sshUser     = '${var.citus_node_user}'
      $sshOpts     = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
      $endpoints   = '${local.citus_etcd_client_endpoints}'
      $initCluster = '${local.citus_etcd_initial_cluster}'
      $timeoutMin  = ${var.citus_cluster_timeout_minutes}

      $members = @(
%{for host, m in local.citus_etcd_members_active~}
        @{ Host='${host}'; VmIp='${m.vm_ip}'; PeerIp='${m.peer_ip}' },
%{endfor~}
        $null
      ) | Where-Object { $_ -ne $null }

      Write-Host "[citus-etcd-bootstrap] $($members.Count) members; initial-cluster=$initCluster; client endpoints=$endpoints"

      # ─── Stage 1: render etcd.conf.yml + endpoints + start in parallel ─────
      foreach ($m in $members) {
        $configBody = @"
# Generated by role-overlay-citus-etcd-bootstrap.tf -- Phase 0.P
# DO NOT EDIT BY HAND -- terraform overlay re-applies on every apply.
name: $($m.Host)
data-dir: /var/lib/nexus-etcd
listen-peer-urls: https://$($m.PeerIp):2380
listen-client-urls: https://$($m.VmIp):2379,https://$($m.PeerIp):2379,https://127.0.0.1:2379
initial-advertise-peer-urls: https://$($m.PeerIp):2380
advertise-client-urls: https://$($m.VmIp):2379
initial-cluster: $initCluster
initial-cluster-token: nexus-citus-etcd
initial-cluster-state: new
peer-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: true
client-transport-security:
  cert-file: /etc/nexus-etcd/tls/server-cert.pem
  key-file: /etc/nexus-etcd/tls/server-key.pem
  trusted-ca-file: /etc/nexus-etcd/tls/ca.pem
  client-cert-auth: true
auto-compaction-mode: periodic
auto-compaction-retention: "1"
quota-backend-bytes: 2147483648
"@
        $configB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes(($configBody -replace "`r`n","`n")))

        $stage = @"
set -euo pipefail
echo '$configB64' | base64 -d | sudo tee /etc/nexus-etcd/etcd.conf.yml > /dev/null
sudo chown root:etcd /etc/nexus-etcd/etcd.conf.yml
sudo chmod 0640 /etc/nexus-etcd/etcd.conf.yml

echo '$endpoints' | sudo tee /etc/nexus-etcd/endpoints > /dev/null
sudo chown root:etcd /etc/nexus-etcd/endpoints
sudo chmod 0644 /etc/nexus-etcd/endpoints

sudo systemctl daemon-reload
sudo systemctl enable nexus-etcd.service
echo CONFIG_OK
"@
        $stageB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($stage))
        $out = (ssh @sshOpts "$sshUser@$($m.VmIp)" "echo '$stageB64' | base64 -d | bash" 2>&1 | Out-String).Trim()
        if ($out -notmatch 'CONFIG_OK') {
          throw "[citus-etcd-bootstrap] $($m.Host): etcd.conf.yml staging failed -- $out"
        }
        Write-Host "[citus-etcd-bootstrap] $($m.Host): config rendered + service enabled"
      }

      Write-Host "[citus-etcd-bootstrap] starting nexus-etcd.service on all $($members.Count) members in parallel..."
      $members | ForEach-Object -ThrottleLimit 3 -Parallel {
        $m = $_
        $opts = @('-o','ConnectTimeout=10','-o','BatchMode=yes','-o','StrictHostKeyChecking=no')
        ssh @opts "$using:sshUser@$($m.VmIp)" "sudo systemctl start nexus-etcd.service" 2>&1 | Out-Null
      }

      # ─── Stage 2: wait for leader election ─────────────────────────────────
      Write-Host "[citus-etcd-bootstrap] waiting for cluster leader election..."
      $deadline      = (Get-Date).AddMinutes($timeoutMin)
      $leaderId      = $null
      $okHostIndex   = $null
      while ((Get-Date) -lt $deadline) {
        for ($i = 0; $i -lt $members.Count; $i++) {
          $m = $members[$i]
          $probe = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo /usr/local/sbin/nexus-etcdctl endpoint status --write-out=json 2>/dev/null" 2>&1 | Out-String).Trim()
          # Non-zero leader id (uint64) == cluster quorate. Each node's own
          # endpoint may fail to dial via its 127.0.1.1 /etc/hosts entry; any
          # response carrying a non-zero leader proves quorum (0.G.4 lesson #8).
          if ($probe -match '"leader":\s*([1-9][0-9]*)') {
            $leaderId    = $matches[1]
            $okHostIndex = $i
            break
          }
        }
        if ($leaderId) { break }
        Start-Sleep -Seconds 5
      }
      if (-not $leaderId) {
        foreach ($m in $members) {
          $j = (ssh @sshOpts "$sshUser@$($m.VmIp)" "sudo journalctl -u nexus-etcd.service --no-pager -n 30" 2>&1 | Out-String)
          Write-Host "--- journal $($m.Host) ---"
          Write-Host $j
        }
        throw "[citus-etcd-bootstrap] no leader elected within $timeoutMin min"
      }
      Write-Host "[citus-etcd-bootstrap] cluster has elected a leader (member_id=$leaderId; observed from $($members[$okHostIndex].Host))"

      # ─── Stage 3: put/get round-trip via cert auth (no RBAC) ──────────────
      $okMember = $members[$okHostIndex]
      $verifyStage = @'
set -euo pipefail
sudo /usr/local/sbin/nexus-etcdctl put /nexus/citus/etcd-bootstrap/marker "$(date -u +%FT%TZ)" >/dev/null
VAL=$(sudo /usr/local/sbin/nexus-etcdctl get /nexus/citus/etcd-bootstrap/marker --print-value-only)
if [ -z "$VAL" ]; then
  echo "[citus-etcd-bootstrap verify] ERROR: put-then-get round-trip returned empty" >&2
  exit 1
fi
echo "[citus-etcd-bootstrap verify] put-then-get round-trip OK (value=$VAL)"
'@
      $verifyB64 = [Convert]::ToBase64String([System.Text.UTF8Encoding]::new($false).GetBytes($verifyStage))
      $verifyOut = (ssh @sshOpts "$sshUser@$($okMember.VmIp)" "echo '$verifyB64' | base64 -d | bash" 2>&1 | Out-String)
      if ($LASTEXITCODE -ne 0) {
        Write-Host $verifyOut.Trim()
        throw "[citus-etcd-bootstrap] post-leader verify failed (rc=$LASTEXITCODE)"
      }
      Write-Host $verifyOut.Trim()

      Write-Host "[citus-etcd-bootstrap] cluster ready: $($members.Count) members, client-cert-auth mTLS, no RBAC password."
    PWSH
  }
}
